apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bernardolsp/studies
    targetRevision: HEAD
    path: forked-application/k8s-config
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  